export const INITIAL_BANKS: string[] = [
  'Islami Bank Bangladesh',
  'Sonali Bank',
  'Janata Bank',
  'Agrani Bank',
  'Agrani Bank LTD',
  'Rupali Bank',
  'Pubali Bank',
  'Pubali Bank LTD',
  'Dutch-Bangla Bank',
  'Dutch Bangla Bank',
  'Bank Asia',
  'Bank Asia LTD',
  'City Bank',
  'City Bank PLC',
  'THE CITY BANK',
  'Bkash',
  'Nagad',
  'BRAC Bank',
  'NRB Bank',
  'IFIC Bank',
  'Shahjalal Islami Bank',
  'SHAHJALAL ISLAMI BANK',
  'Al Arafa Islami Bank',
  'Krishi Bank Bangladesh',
  'RAJSHAHI KRISHI BANK',
  'NATIONAL BANK PLC',
  'THE PREMIER BANK',
  'Jamuna Bank',
  'JUMUNA BANK LTD',
  'Eastern Bank',
  'Prime Bank',
  'UCB',
  'Mutual Trust Bank',
  'NCC Bank',
  'Dhaka Bank',
  'Southeast Bank',
  'Mercantile Bank',
  'One Bank',
  'Trust Bank',
  'Social Islami Bank',
  'Standard Bank',
  'Meghna Bank',
  'Midland Bank',
  'Community Bank Bangladesh',
  'Modhumoti Bank',
  'AB Bank',
];

export const INITIAL_REFERENCES: string[] = [
  'Kaka',
  "Humaiun Kaka's Assistant",
];

export const DEFAULT_BANKS = INITIAL_BANKS;
export const DEFAULT_REFERENCES = INITIAL_REFERENCES;
